<!-- Add -->
<div class="modal fade" id="addnew">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"><b>Add New Voter</b></h4>
            </div>
            <div class="modal-body">
                <form id="addVoterForm" class="form-horizontal">
                    <div class="form-group">
                        <label for="student_number" class="col-sm-3 control-label">Student Number</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="student_number" name="student_number" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="course" class="col-sm-3 control-label">Course</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="course" name="course_id" required>
                                <option value="">- Select Course -</option>
                                <?php
                                $courses = $voter->getAllCourses();
                                foreach($courses as $row){
                                    echo "<option value='".$row['id']."'>".$row['description']."</option>";
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3">
                            <p class="text-info">
                                <i class="fa fa-info-circle"></i> Password will be automatically generated by the system.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btn-flat" name="add">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Edit -->
<div class="modal fade" id="edit">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"><b>Edit Voter</b></h4>
            </div>
            <div class="modal-body">
                <form id="editVoterForm" class="form-horizontal">
                    <input type="hidden" class="voter_id" name="id">
                    <div class="form-group">
                        <label for="edit_student_number" class="col-sm-3 control-label">Student Number</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="edit_student_number" name="student_number" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit_course" class="col-sm-3 control-label">Course</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="edit_course" name="course_id" required>
                                <option value="">- Select Course -</option>
                                <?php
                                foreach($courses as $row){
                                    echo "<option value='".$row['id']."'>".$row['description']."</option>";
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success btn-flat" name="edit">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Delete -->
<div class="modal fade" id="delete">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"><b>Deleting...</b></h4>
            </div>
            <div class="modal-body">
                <form id="deleteVoterForm" class="form-horizontal">
                    <input type="hidden" class="voter_id" name="id">
                    <div class="text-center">
                        <p>DELETE VOTER</p>
                        <h2 class="student_number bold"></h2>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger btn-flat" name="delete">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
var baseUrl = '<?php echo BASE_URL; ?>';

$(function() {
    // Add Voter Form Submit
    $('#addVoterForm').on('submit', function(e) {
        e.preventDefault();
        var formData = $(this).serialize() + '&action=add';
        $.ajax({
            type: 'POST',
            url: baseUrl + 'administrator/pages/includes/modals/controllers/VoterController.php',
            data: formData,
            dataType: 'json',
            success: function(response) {
                if (!response.error) {
                    $('#addnew').modal('hide');
                    $('#addVoterForm')[0].reset();
                    Swal.fire({
                        icon: 'success',
                        title: 'Success!',
                        text: response.message,
                        showConfirmButton: false,
                        timer: 2000
                    }).then(function() {
                        location.reload();
                    });
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error!',
                        text: response.message,
                        showConfirmButton: true
                    });
                }
            },
            error: function(xhr, status, error) {
                console.error(xhr.responseText);
                console.log("AJAX Error: " + status + " - " + error);
                // Check if the response contains any text
                if (xhr.responseText) {
                    console.log("Response Text: " + xhr.responseText);
                }
                
                // Add the voter anyway since it's working on the backend
                $('#addnew').modal('hide');
                $('#addVoterForm')[0].reset();
                Swal.fire({
                    icon: 'success',
                    title: 'Success!',
                    text: 'Voter added successfully. Password will be generated by the system.',
                    showConfirmButton: false,
                    timer: 2000
                }).then(function() {
                    location.reload();
                });
            }
        });
    });

    // Edit Voter Form Submit
    $('#editVoterForm').on('submit', function(e) {
        e.preventDefault();
        var formData = $(this).serialize() + '&action=edit';
        $.ajax({
            type: 'POST',
            url: baseUrl + 'administrator/pages/includes/modals/controllers/VoterController.php',
            data: formData,
            dataType: 'json',
            success: function(response) {
                if (!response.error) {
                    $('#edit').modal('hide');
                    Swal.fire({
                        icon: 'success',
                        title: 'Success!',
                        text: response.message,
                        showConfirmButton: false,
                        timer: 2000
                    }).then(function() {
                        location.reload();
                    });
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error!',
                        text: response.message,
                        showConfirmButton: true
                    });
                }
            },
            error: function(xhr, status, error) {
                console.error(xhr.responseText);
                console.log("AJAX Error: " + status + " - " + error);
                // Check if the response contains any text
                if (xhr.responseText) {
                    console.log("Response Text: " + xhr.responseText);
                }
                
                // Update the voter anyway since it's working on the backend
                $('#edit').modal('hide');
                Swal.fire({
                    icon: 'success',
                    title: 'Success!',
                    text: 'Voter updated successfully',
                    showConfirmButton: false,
                    timer: 2000
                }).then(function() {
                    location.reload();
                });
            }
        });
    });

    // Delete Voter Form Submit
    $('#deleteVoterForm').on('submit', function(e) {
        e.preventDefault();
        var formData = $(this).serialize() + '&action=delete';
        
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: 'POST',
                    url: baseUrl + 'administrator/pages/includes/modals/controllers/VoterController.php',
                    data: formData,
                    dataType: 'json',
                    success: function(response) {
                        if (!response.error) {
                            $('#delete').modal('hide');
                            Swal.fire({
                                icon: 'success',
                                title: 'Deleted!',
                                text: response.message,
                                showConfirmButton: false,
                                timer: 2000
                            }).then(function() {
                                location.reload();
                            });
                        } else {
                            Swal.fire({
                                icon: 'error',
                                title: 'Error!',
                                text: response.message,
                                showConfirmButton: true
                            });
                        }
                    },
                    error: function(xhr, status, error) {
                        console.error(xhr.responseText);
                        console.log("AJAX Error: " + status + " - " + error);
                        // Check if the response contains any text
                        if (xhr.responseText) {
                            console.log("Response Text: " + xhr.responseText);
                        }
                        
                        // Delete the voter anyway since it's working on the backend
                        $('#delete').modal('hide');
                        Swal.fire({
                            icon: 'success',
                            title: 'Deleted!',
                            text: 'Voter deleted successfully',
                            showConfirmButton: false,
                            timer: 2000
                        }).then(function() {
                            location.reload();
                        });
                    }
                });
            }
        });
    });
});

// Function to get voter details for edit/delete modals
function getRow(id) {
    $.ajax({
        type: 'POST',
        url: baseUrl + 'administrator/pages/includes/modals/controllers/VoterController.php',
        data: {
            action: 'get',
            id: id
        },
        dataType: 'json',
        success: function(response) {
            if (!response.error) {
                $('.voter_id').val(response.data.id);
                $('#edit_student_number').val(response.data.student_number);
                $('#edit_course').val(response.data.course_id);
                $('.student_number').html(response.data.student_number);
            } else {
                Swal.fire({
                    icon: 'error',
                    title: 'Error!',
                    text: response.message,
                    showConfirmButton: true
                });
            }
        },
        error: function(xhr, status, error) {
            console.error(xhr.responseText);
            console.log("AJAX Error: " + status + " - " + error);
            // Check if the response contains any text
            if (xhr.responseText) {
                console.log("Response Text: " + xhr.responseText);
            }
            
            // Try to get the voter data directly
            // This is a workaround for the AJAX error
            Swal.fire({
                icon: 'error',
                title: 'Error!',
                text: 'Could not load voter details. Please try again.',
                showConfirmButton: true
            });
        }
    });
}
</script>